version: '3.6'

services:

  quiz-bot:
    build:
      context: .
    working_dir:
      /quiz_bot/
    env_file:
      - .env
    command:
      /quiz_bot/entrypoint.sh
    volumes:
      - ./data:/data/
      - ./src:/quiz_bot/src/
    depends_on:
     - redis

  redis:
    image: redis
    ports:
      - "6379:6379"